version: "3"
services:
  django-app:
    build:
      context: .
      args:
        GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS
    ports:
      - "9101:8000"
    volumes:
      - $HOME/.gcp:/usr/gcp
      - ./:/app
    tty: true
    stdin_open: true
    depends_on:
      - django-db
    env_file:
      - .env
  django-db:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    ports:
      - 9102:3306
    tty: true
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tswebdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - django-db:/var/lib/mysql
  redis:
    image: "redis:latest"
    ports:
      - "9103:6379"
    volumes:
      - ./data/redis:/data
volumes:
  django-db:
