# Generated by Django 3.1 on 2020-08-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
            ],
        ),
    ]
